feat: Bb 105 create a reusable footer component
bcgov/nr-sustainment-capstone-2024 pull request #126
Opened 2024-06-03 21:47 UTC by GDamaso

# Description

Created our footer component with BC Design Tokens and emotion styled components

## Type of changes

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-06-03 22:58 UTC, kcaparas1630 requested changes
On Mobile View, assuming width 320, this is what I get. 
![image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/144957476/8a4e123f-92c2-4540-a210-71d730a876c8)
We should make it mobile-first then work on desktop next.

2024-06-04 02:57 UTC, LocalNewsTV commented on frontend/dev-dist/registerSW.js
Everything included in `dev-dist` should be removed, this is now being `.gitignored` 
The files are generative from running in dev and aren't needed

2024-06-04 02:57 UTC, LocalNewsTV commented on frontend/src/Views/Footer.tsx
> +      <a href="https://www2.gov.bc.ca/gov/content/industry/agriculture-seafood/agricultural-land-and-environment/soil-nutrients/nutrient-management/nutrient-management-calculator/support-for-the-bc-n
Suggestion: Might be valuable to move your URLS into variables held in the component
1. Simplifies the `tsx`
2. Adds intent to what the urls are for (These urls are pretty self-explanatory though)

2024-06-04 03:24 UTC, LocalNewsTV commented
I mentioned this before on the `Header` ticket 
Please include screenshots of mockups and your components in your PR :)
It helps me review you more fairly, and not operate on the assumptions of what things are meant to look like. 
Its also a good thing to get used to it, since it makes PRs far more descriptive.

2024-06-04 23:27 UTC, GDamaso commented
@DerekRoberts  Backend is failing out of nowhere here. Any insights?

```bash
Run # Expand for route verification
  # Expand for route verification
  
  # Check for URL (route + path)
  URL_HOST_PATH=nr-sustainment-capstone-2024-126-backend.apps.silver.devops.gov.bc.ca/api/health
  if [ -z "${URL_HOST_PATH}" ]; then
    echo "No route found. Skipping."
    exit 0
  fi
  echo -e "URL: ${URL_HOST_PATH}"
  
  # Curl and verify
  TRIES="3"
  SECONDS="15"
  for (( i=0; i<"${TRIES}"; i++ )); do
    HTTP_CODE=$(curl -Lso /dev/null -w "%{http_code}" "${URL_HOST_PATH}")
    if [ "${HTTP_CODE}" -eq 200 ]; then
      echo -e "Route verification successful!\n"
      exit 0
    fi
    echo -e "HTTP_CODE:${HTTP_CODE}, Try: #${i}"
    sleep "${SECONDS}"
  done
  echo -e "\nRoute verification failed"
  exit 1
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/9210e767-6a5e-4ee5-8ae8-e59e473e1ff7.sh
URL: nr-sustainment-capstone-2024-126-backend.apps.silver.devops.gov.bc.ca/api/health
HTTP_CODE:503, Try: #0
HTTP_CODE:503, Try: #1
HTTP_CODE:503, Try: #2

Route verification failed
Error: Process completed with exit code 1.
```

No change in the backend has been done in a while and the header component PR doesn't seem to be deployed to our [openshift domain](https://nr-sustainment-capstone-2024-126-frontend.apps.silver.devops.gov.bc.ca/):

<img src="https://github.com/bcgov/nr-sustainment-capstone-2024/assets/80939533/be68d280-f886-4ced-94ab-7be3af1d0e07" width=300px>

But a part of this PR seems to have been deployed, since there is a footer component over there.

Thanks in advance :smile:

2024-06-05 16:29 UTC, DerekRoberts commented
@GDamaso Good troubleshooting!  :)

I'm off this week and really appreciate your efforts.  Please pull the most recent change, which bumps verification retries from 3 to 5, which can't hurt.

Backend is still failing, but not during deployment.  Are you okay with working on this and we team up Monday there's anything left?
```
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
```
https://console.apps.silver.devops.gov.bc.ca/k8s/ns/b4cd74-dev/pods/nr-sustainment-capstone-2024-126-backend-84bdd6f944-h987k/logs

2024-06-05 16:42 UTC, GDamaso commented
@DerekRoberts I don't mind at all. 
Thanks for all the help you've put into our project already,  we really appreciate it!
Enjoy your week off :tada:

2024-06-05 16:50 UTC, kcaparas1630 approved these changes
LGTM 🚀

2024-06-05 17:25 UTC, merged